objects/ccrz__E_Product__c.object
<CustomObject>
</CustomObject>

objects/CPQB2BLog__c.object
<CustomObject>
    <description>Custom object used for storing data associated to failed mapped records from CPQB2B syncing processes.</description>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Stores the error message that occurs when a record fails to update during the CPQ/B2B syncing process.</description>
        <label>Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Process_Type__c</fullName>
        <description>Stores the process type that was executing at the time of the record error.</description>
        <label>Process Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <description>Represents the record id of the record that failed to update through CPQ/B2B syncing process.</description>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Record_Id__c</fullName>
        <description>Stores the record Id of the source record from which data was attempted to be copied during the CPQ/B2B syncing process.</description>
        <label>Source Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>Stores the error stack trace message that was generated for the failed record.</description>
        <label>Stack Trace</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Triggering_Event__c</fullName>
        <description>Stores the triggering event type of the failed record.</description>
        <label>Triggering Event</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Batch</fullName>
                </value>
                <value>
                    <fullName>Future Call</fullName>
                </value>
                <value>
                    <fullName>Platform Event</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CPQB2B Log</label>
    <nameField>
        <label>CPQB2B Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQB2B Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CPQB2BLoggingServiceTest.cls
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */

@isTest
public class CPQB2BLoggingServiceTest {
    
    @isTest
    public static void testExceptionLoggingService() {
        Test.startTest();
        CPQB2BLogger logger = new CPQB2BLogger();

        List<ccrz__E_Product__c> ccProdList = new List<ccrz__E_Product__c>();
        ccrz__E_Product__c ccProduct1 = new ccrz__E_Product__c();
        ccProduct1.Name = 'CPQB2B - TestProduct1';
        ccProduct1.ccrz__SKU__c = '1234';
        ccProdList.add(ccProduct1);

        logger.log(CPQB2BProcessType.SKU.name(),'Batch',new DMLException(),ccProdList);          

        logger.write();

        Test.stopTest();
        
        List<CPQB2BLog__c> logList = [Select Id, Process_Type__c,Record_Id__c,Source_Record_Id__c,Error_Message__c,Stack_Trace__c,Triggering_Event__c, CreatedDate FROM CPQB2BLog__c];
        System.assertEquals(1,logList.size(),'The returned list size of ' + logList.size() + ' does not match the expected value of 1.');

    }
}