objects/CPQ_B2B_Connector__e.object
<CustomObject>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>The object Id that we want to use the connector to sync data</description>
        <label>Object Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CPQ B2B Connector Event</label>
    <pluralLabel>CPQ B2B Connectors</pluralLabel>
</CustomObject>

objects/CPQB2BQueueItem__c.object
<CustomObject>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Marked as External Id to create an index.</description>
        <externalId>true</externalId>
        <label>Priority</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <description>Contains the SFDC Id of the record to be processed.</description>
        <externalId>true</externalId>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;NEW&quot;</defaultValue>
        <description>Marked as External Id to create an index.</description>
        <externalId>true</externalId>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CPQB2B Queue Item</label>
    <nameField>
        <displayFormat>QI-{000000000}</displayFormat>
        <label>CQPB2BQueue Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPQB2B Queue Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CPQB2BTestInt.cls
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */

public abstract class CPQB2BTestInt {
	
    public abstract void run(Id id, String sObjectName);
    
    public class RunWithPlatformEvent extends CPQB2BTestInt {
    
        public override void run(Id id, String sObjectName) {
            // fire the platform event
            CPQ_B2B_Connector__e e = new CPQ_B2B_Connector__e();
            e.Object_Id__c = Id;
    
            Database.SaveResult sr = EventBus.publish(e);
            Test.getEventBus().deliver(); 
        }        
    }
    
    public class RunWithQueue extends CPQB2BTestInt {
    
        public override void run(Id id, String sObjectName) {
            // create the queueItem and enqueue job
            CPQB2BQueueItem__c qi = new CPQB2BQueueItem__c();
            qi.Object__c = sObjectName;
            qi.RecordId__c = Id;
            qi.Status__c = 'NEW';
            qi.Priority__c = 0;
            insert qi;
            System.enqueueJob( new CPQB2BQueueItemWorker() );
        }
        
    }    
    
    
}