objects/CPQ_B2B_Mapping__mdt.object
<CustomObject>
    <description>Defines the custom mapping fields for the CPQ B2B Connector (used in addition to the standard fields)</description>
    <fields>
        <fullName>Destination_Field__c</fullName>
        <description>The Destination Field</description>
        <inlineHelpText>The Destination Field</inlineHelpText>
        <label>Destination Field</label>
        <metadataRelationshipControllingField>CPQ_B2B_Mapping__mdt.Destination_Object__c</metadataRelationshipControllingField>
        <referenceTo>FieldDefinition</referenceTo>
        <relationshipLabel>CPQ_B2B_Mappings1</relationshipLabel>
        <relationshipName>CPQ_B2B_Mappings1</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Destination_Object__c</fullName>
        <description>The Destination Object</description>
        <inlineHelpText>The Destination Object</inlineHelpText>
        <label>Destination Object</label>
        <referenceTo>EntityDefinition</referenceTo>
        <relationshipLabel>CPQ_B2B_Mappings1</relationshipLabel>
        <relationshipName>CPQ_B2B_Mappings1</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Field_Mapping_Service_Class__c</fullName>
        <description>If this field is populated, the Connector will call this class to obtain the field mapping value</description>
        <inlineHelpText>If this field is populated, the Connector will call this class to obtain the field mapping value</inlineHelpText>
        <label>Field Mapping Service Class</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <description>The Connector process that uses the mapping records</description>
        <inlineHelpText>The Connector process that uses the mapping records</inlineHelpText>
        <label>Process</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SKU</fullName>
                    <default>true</default>
                    <label>SKU</label>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>CartToQuote</fullName>
                    <label>Cart To Quote</label>
                </value>
                <value>
                    <fullName>CCOrderToOrder</fullName>
                    <label>CC Order To Order</label>
                </value>
                <value>
                    <fullName>OrderToCCOrder</fullName>
                    <label>CPQ Order to CC Order</label>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>OrdertToCCOrder</fullName>
                    <isActive>false</isActive>
                    <label>Order to CC Order</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Field__c</fullName>
        <description>The Source Field</description>
        <inlineHelpText>The Source Field</inlineHelpText>
        <label>Source Field</label>
        <metadataRelationshipControllingField>CPQ_B2B_Mapping__mdt.Source_Object__c</metadataRelationshipControllingField>
        <referenceTo>FieldDefinition</referenceTo>
        <relationshipLabel>CPQ_B2B_Mappings</relationshipLabel>
        <relationshipName>CPQ_B2B_Mappings</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Source_Object__c</fullName>
        <description>The Source Object</description>
        <inlineHelpText>The Source Object</inlineHelpText>
        <label>Source Object</label>
        <referenceTo>EntityDefinition</referenceTo>
        <relationshipLabel>CPQ_B2B_Mappings</relationshipLabel>
        <relationshipName>CPQ_B2B_Mappings</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Source_Value__c</fullName>
        <description>This field is used for setting a field on a destination object to a static text value.</description>
        <inlineHelpText>When this is populated, a static text value can be set on the destination object. This is good for setting default picklist values.</inlineHelpText>
        <label>Source Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CPQ B2B Mapping</label>
    <pluralLabel>CPQ B2B Mappings</pluralLabel>
</CustomObject>

classes/CPQB2BMappingSelector.cls
/**
 * Created by javierarroyo on 2/12/20.
 * @description This class encapsulates the logic for obtaining the custom mapping fields used in the CPQ-B2B Connector
 *
 */
public class CPQB2BMappingSelector {

    /**
     * @description find the mappings for the process. Note: this class returns a convenience list of attributes that
     * map directly to the CPQ_B2B_Mapping__mdt meta data.
     * @param p - the Enumeration that identifies the process to query
     *
     * @return an instance of CPQB2BMappingSelector
     */
    public static List<CPQB2BBaseFieldMapping> getMappingByProcess(CPQB2BProcessType p) {
        List<CPQ_B2B_Mapping__mdt> mappings = [
                Select
                Source_Object__r.QualifiedApiName,
                Source_Field__r.QualifiedApiName,
                Destination_Object__r.QualifiedApiName,
                Destination_Field__r.QualifiedApiName,
                Field_Mapping_Service_Class__c,
                Source_Value__c
                From
                    CPQ_B2B_Mapping__mdt
                WHERE
                    Process__c =: p.name()
                ];
        if (mappings == null || mappings.size() < 1) return null;
        
        List<CPQB2BBaseFieldMapping> mapList = new List<CPQB2BBaseFieldMapping>();

        for(CPQ_B2B_Mapping__mdt m: mappings) {
            CPQB2BBaseFieldMapping fieldMap;
            if (m.Field_Mapping_Service_Class__c != null) {
                Type t = Type.forName(m.Field_Mapping_Service_Class__c );
                fieldMap = (CPQB2BBaseFieldMapping)t.newInstance();
                fieldMap.setFieldMapping(m);
            } else {
                fieldMap = new CPQB2BFieldMapping(m);
            }
            mapList.add(fieldMap); 
        }

        return mapList;
    }

    /**
     * @description retrieves the custom defined quote status value
     * when a quote is generated from a cart
     *
     * @return a String value of custom defined quote status
     */
    public static String getCustomQuoteStatus() {
        List<CPQ_B2B_Mapping__mdt> mappings = [
                Select 
                    Source_Value__c
                From
                    CPQ_B2B_Mapping__mdt
                WHERE
                    Process__c = 'CartToQuote'
                AND 
                    QualifiedApiName = 'QuoteStatusFieldUpdate'
                LIMIT 1];
        if (mappings == null || mappings.size() < 1) return null;

        return mappings[0].Source_Value__c;
    }

    /**
     * @description retrieves the custom defined cart status value
     * when a quote is generated from a cart
     *
     * @return a String value of custom defined cart status
     */
    public static String getCustomCartStatus() {
        List<CPQ_B2B_Mapping__mdt> mappings = [
                Select 
                    Source_Value__c
                From
                    CPQ_B2B_Mapping__mdt
                WHERE
                    Process__c = 'CartToQuote'
                AND 
                    QualifiedApiName = 'CartStatusFieldUpdate'
                LIMIT 1];
        if (mappings == null || mappings.size() < 1) return null;

        return mappings[0].Source_Value__c;
    }

    /**
     * @description retrieves the custom defined order status value
     * when a quote is generated from a cc order
     *
     * @return a String value of custom defined order status
     */
    public static String getCustomOrderStatus() {
        List<CPQ_B2B_Mapping__mdt> mappings = [
                Select 
                    Source_Value__c
                From
                    CPQ_B2B_Mapping__mdt
                WHERE
                    Process__c = 'CCOrderToOrder'
                    AND 
                    QualifiedApiName = 'OrderStatusFieldUpdate'
                LIMIT 1];

        if (mappings == null || mappings.size() < 1) return null;

        return mappings[0].Source_Value__c;
    }

    /**
     * @description retrieves the custom defined opportunity stage value
     * when a oportunity is generated from a cc order
     *
     * @return a String value of custom defined opportunity stage
     */
    public static String getCustomOpportunityStage() {
        List<CPQ_B2B_Mapping__mdt> mappings = [
                Select 
                    Source_Value__c
                From
                    CPQ_B2B_Mapping__mdt
                WHERE
                    Process__c = 'CCOrderToOrder'
                    AND 
                    QualifiedApiName = 'OpportunityStageFieldUpdate'
                LIMIT 1];

        if (mappings == null || mappings.size() < 1) return null;

        return mappings[0].Source_Value__c;
    }
}