objects/CPQ_B2B_Mapping__mdt.object
<CustomObject>
    <description>Defines the custom mapping fields for the CPQ B2B Connector (used in addition to the standard fields)</description>
    <fields>
        <fullName>Destination_Field__c</fullName>
        <description>The Destination Field</description>
        <inlineHelpText>The Destination Field</inlineHelpText>
        <label>Destination Field</label>
        <metadataRelationshipControllingField>CPQ_B2B_Mapping__mdt.Destination_Object__c</metadataRelationshipControllingField>
        <referenceTo>FieldDefinition</referenceTo>
        <relationshipLabel>CPQ_B2B_Mappings1</relationshipLabel>
        <relationshipName>CPQ_B2B_Mappings1</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Destination_Object__c</fullName>
        <description>The Destination Object</description>
        <inlineHelpText>The Destination Object</inlineHelpText>
        <label>Destination Object</label>
        <referenceTo>EntityDefinition</referenceTo>
        <relationshipLabel>CPQ_B2B_Mappings1</relationshipLabel>
        <relationshipName>CPQ_B2B_Mappings1</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Field_Mapping_Service_Class__c</fullName>
        <description>If this field is populated, the Connector will call this class to obtain the field mapping value</description>
        <inlineHelpText>If this field is populated, the Connector will call this class to obtain the field mapping value</inlineHelpText>
        <label>Field Mapping Service Class</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Field__c</fullName>
        <description>The Source Field</description>
        <inlineHelpText>The Source Field</inlineHelpText>
        <label>Source Field</label>
        <metadataRelationshipControllingField>CPQ_B2B_Mapping__mdt.Source_Object__c</metadataRelationshipControllingField>
        <referenceTo>FieldDefinition</referenceTo>
        <relationshipLabel>CPQ_B2B_Mappings</relationshipLabel>
        <relationshipName>CPQ_B2B_Mappings</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Source_Object__c</fullName>
        <description>The Source Object</description>
        <inlineHelpText>The Source Object</inlineHelpText>
        <label>Source Object</label>
        <referenceTo>EntityDefinition</referenceTo>
        <relationshipLabel>CPQ_B2B_Mappings</relationshipLabel>
        <relationshipName>CPQ_B2B_Mappings</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Source_Value__c</fullName>
        <description>This field is used for setting a field on a destination object to a static text value.</description>
        <inlineHelpText>When this is populated, a static text value can be set on the destination object. This is good for setting default picklist values.</inlineHelpText>
        <label>Source Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CPQ B2B Mapping</label>
    <pluralLabel>CPQ B2B Mappings</pluralLabel>
</CustomObject>

classes/CPQB2BBaseFieldMapping.cls
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */

/**
* @author Ashlee Zeigler
* @date 3-3-2020

* @description Base Class for field mapping that can be overridden so that
* custom mapping classes can be defined within the custom metadata
*/
public abstract class CPQB2BBaseFieldMapping {
    public String sourceObject;
    public String destObject;
    public String sourceField;
    public String destField;
    public String serviceClass;
    public String sourceValue;

    /**
     * CPQB2BBaseFieldMapping Default constructor 
     * @param  srcField  
     * @param  destField 
     * @return CPQB2BBaseFieldMapping instance
     */
    public CPQB2BBaseFieldMapping() {}

     /**
     * CPQB2BBaseFieldMapping Constructor taking only a srcField and destField as parameters
     * @param  srcField  
     * @param  destField 
     * @return           CPQB2BBaseFieldMapping instance
     */
    public CPQB2BBaseFieldMapping(String srcField, String destField){
        this.sourceField = srcField;
        this.destField = destField;
    }

    /**
     * CPQB2BBaseFieldMapping Constructor taking CPQ_B2B_Mapping__mdt
     * @param  CPQ_B2B_Mapping__mdt  customFieldMap
     * @return           CPQB2BBaseFieldMapping instance
     */
    public CPQB2BBaseFieldMapping(CPQ_B2B_Mapping__mdt customFieldMap) {
        this.sourceObject = customFieldMap.Source_Object__r.QualifiedApiName;
        this.destObject = customFieldMap.Destination_Object__r.QualifiedApiName;
        this.sourceField = customFieldMap.Source_Field__r.QualifiedApiName;
        this.destField = customFieldMap.Destination_Field__r.QualifiedApiName;
        this.serviceClass = customFieldMap.Field_Mapping_Service_Class__c;
        this.sourceValue = customFieldMap.Source_Value__c;
    }

    /**
     * Set the Field Mapping for instances of the class that are dynamically instantiated
     * @param  CPQ_B2B_Mapping__mdt  customFieldMap
     */
    public void setFieldMapping(CPQ_B2B_Mapping__mdt customFieldMap) {
        this.sourceObject = customFieldMap.Source_Object__r.QualifiedApiName;
        this.destObject = customFieldMap.Destination_Object__r.QualifiedApiName;
        this.sourceField = customFieldMap.Source_Field__r.QualifiedApiName;
        this.destField = customFieldMap.Destination_Field__r.QualifiedApiName;
        this.serviceClass = customFieldMap.Field_Mapping_Service_Class__c;
        this.sourceValue = customFieldMap.Source_Value__c;
    }

    /**
     * copyValue abstract method to override the mapping between object 
     * @param SObject source
     * @param SObject destination
     */
    public abstract void copyValue(SObject source, SObject dest);
}