objects/CPQB2BLog__c.object
<CustomObject>
    <description>Custom object used for storing data associated to failed mapped records from CPQB2B syncing processes.</description>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Stores the error message that occurs when a record fails to update during the CPQ/B2B syncing process.</description>
        <label>Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Process_Type__c</fullName>
        <description>Stores the process type that was executing at the time of the record error.</description>
        <label>Process Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <description>Represents the record id of the record that failed to update through CPQ/B2B syncing process.</description>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Record_Id__c</fullName>
        <description>Stores the record Id of the source record from which data was attempted to be copied during the CPQ/B2B syncing process.</description>
        <label>Source Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>Stores the error stack trace message that was generated for the failed record.</description>
        <label>Stack Trace</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Triggering_Event__c</fullName>
        <description>Stores the triggering event type of the failed record.</description>
        <label>Triggering Event</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Batch</fullName>
                </value>
                <value>
                    <fullName>Future Call</fullName>
                </value>
                <value>
                    <fullName>Platform Event</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CPQB2B Log</label>
    <nameField>
        <label>CPQB2B Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQB2B Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CPQB2BLoggingService.cls
/**
* @author Amil Abdallah
* @date 02/21/2020
*
* @description Handles logic to generate log records for any records that fail
* during a CPQ/B2B syncing processes.
*/
public class CPQB2BLoggingService{
    /**
     * logErrorsAsync Translates serialized json log records into CPQB2BLog__c records
     * and inserts them into the database with a future context asynchrounously (@future)
     * @param  errorList Serialized json list of wrapper log records
     */
    @future
    public static void logErrorsAsync(List<String> errorList){

        List<CPQB2BLog> logWrapperList = new List<CPQB2BLog>();
        for(String record : errorList){
            CPQB2BLog logWrapper = (CPQB2BLog) JSON.deserialize(record,CPQB2BLog.class);
            logWrapperList.add(logWrapper);
        }

        List<CPQB2BLog__c> logObjList = CPQB2BLoggingService.getLogsFromWrapper(logWrapperList);

        try{
            Database.insert(logObjList);
        }
        catch(Exception e){
            System.debug(e.getMessage());
        }
        
    }
    /**
     * logErrors Translates serialized json log records into CPQB2BLog__c records
     * and inserts them into the database with a future context
     * @param  errorList Serialized json list of wrapper log records
     */
    public static void logErrors(List<String> errorList){

        List<CPQB2BLog> logWrapperList = new List<CPQB2BLog>();
        for(String record : errorList){
            CPQB2BLog logWrapper = (CPQB2BLog) JSON.deserialize(record,CPQB2BLog.class);
            logWrapperList.add(logWrapper);
        }

        List<CPQB2BLog__c> logObjList = CPQB2BLoggingService.getLogsFromWrapper(logWrapperList);

        try{
            Database.insert(logObjList);
        }
        catch(Exception e){
            System.debug(e.getMessage());
        }
        
    }
    
    /**
     * logBatchErrors Translates serialized json log records into CPQB2BLog__c records
     * and inserts them into the database without a future context
     * @param  errorList Serialized json list of wrapper log records
     */
    public static void logBatchErrors(List<String> errorList){

        List<CPQB2BLog> logWrapperList = new List<CPQB2BLog>();
        for(String record : errorList){
            CPQB2BLog logWrapper = (CPQB2BLog) JSON.deserialize(record,CPQB2BLog.class);
            logWrapperList.add(logWrapper);
        }

        List<CPQB2BLog__c> logObjList = CPQB2BLoggingService.getLogsFromWrapper(logWrapperList);

        try{
            Database.insert(logObjList);
        }
        catch(Exception e){
            System.debug(e.getMessage());
        }
        
    } 

    /**
     * getLogsFromWrapper Translates log wrapper records into CPQB2BLog__c records
     * to be inserted into the database
     * @param  logWrapperList List of log wrapper records
     * @return logObjList List of CPQB2BLog__c records to be inserted
     */
    public static List<CPQB2BLog__c> getLogsFromWrapper(List<CPQB2BLog> logWrapperList){

        List<CPQB2BLog__c> logObjList = new List<CPQB2BLog__c>();

        for(CPQB2BLog logWrapper : logWrapperList){
            logObjList.add(new CPQB2BLog__c(
                Process_Type__c = logWrapper.processType,
                Record_Id__c = logWrapper.recordId,    
                Source_Record_Id__c = logWrapper.sourceId,
                Error_Message__c = logWrapper.message,
                Triggering_Event__c = logWrapper.triggerEvent,
                Stack_Trace__c = logWrapper.stackTrace
            ));
        }
        return logObjList;
    }
}